syscall {
    name: "open"
    num: 2
    retval: FD
    params {
        name: "filename"
        type: PATH
    }
    params { 
        name: "flags"
        type: INT32
    }
    params {
        name: "mode"
        type: INT32
    }
}

syscall {
    name: "openat"
    num: 257
    retval: FD
    params {
        name: "dir_fd"
        type: FD
    }
    params {
        name: "filename"
        type: PATH
    }
    params {
        name: "flags"
        type: INT32
    }
    params {
        name: "mode"
        type: INT32
    }
}

syscall {
    name: "mkdir"
    num: 83
    params {
        name: "pathname"
        type: PATH
    }
    params {
        name: "flags"
        type: INT32
    }
}

syscall {
    name: "mkdirat"
    num: 258
    params {
        name: "dir_fd"
        type: FD
    }
    params {
        name: "pathname"
        type: PATH
    }
    params {
        name: "flags"
        type: INT32
    }
}

syscall {
    name: "symlink"
    num: 88
    params {
        name: "oldname"
        type: PATH
    }
    params {
        name: "newname"
        type: PATH
    }
}

syscall {
    name: "symlinkat"
    num: 266
    params {
        name: "oldname"
        type: PATH
    }
    params {
        name: "newfd"
        type: FD
    }
    params {
        name: "newname"
        type: PATH
    }
}

syscall {
    name: "unlink"
    num: 87
    params {
        name: "pathname"
        type: PATH
    }
}

syscall {
    name: "unlinkat"
    num: 263
    params {
        name: "dir_fd"
        type: FD
    }
    params {
        name: "pathname"
        type: PATH
    }
    params {
        name: "flags"
        type: INT32
    }
}

syscall {
    name: "rmdir"
    num: 84
    params {
        name: "pathname"
        type: PATH       
    }
}

syscall {
    name: "faccessat"
    num: 269
    params {
        name: "dir_fd"
        type: FD
    }
    params {
        name: "filename"
        type: PATH
    }
    params {
        name: "mode"
        type: INT32
    }
}

syscall {
    name: "access"
    num: 21
    params {
        name: "filename"
        type: PATH
    }
    params {
        name: "mode"
        type: INT32
    }
}

syscall {
    name: "fstatat"
    num: 262
    params {
        name: "dir_fd"
        type: FD
    }
    params {
        name: "filename"
        type: PATH
    }
    params {
        name: "statbuf"
        type: OUT_BUFFER
        const_len: 144 
    }
    params {
        name: "flags"
        type: INT32
    }
}

syscall {
    name: "stat"
    num: 4
    params {
        name: "filename"
        type: PATH
    }
    params {
        name: "statbuf"
        type: OUT_BUFFER
        const_len: 144 
    }
}

syscall {
    name: "lstat"
    num: 6
    params {
        name: "filename"
        type: PATH
    }
    params {
        name: "statbuf"
        type: OUT_BUFFER
        const_len: 144 
    }
}

syscall {
    name: "fstat"
    num: 5
    params {
        name: "fd"
        type: FD
    }
    params {
        name: "statbuf"
        type: OUT_BUFFER
        const_len: 144 
    }
}

syscall {
    name: "readlinkat"
    num: 267
    retval: INT32
    params {
        name: "dir_fd"
        type: FD
    }
    params {
        name: "pathname"
        type: PATH
    }
    params {
        name: "buf"
        type: OUT_BUFFER
        len_param_name: "bufsiz" 
    }
    params {
        name: "bufsiz"
        type: INT32
    }
}

syscall {
    name: "readlink"
    num: 89
    retval: INT32
    params {
        name: "pathname"
        type: PATH
    }
    params {
        name: "buf"
        type: OUT_BUFFER
        len_param_name: "bufsiz" 
    }
    params {
        name: "bufsiz"
        type: INT32
    }
}

syscall {
    name: "renameat2"
    num: 316
    params {
        name: "olddfd"
        type: FD
    }
    params {
        name: "oldname"
        type: PATH
    }
    params {
        name: "newdfd"
        type: FD
    }
    params {
        name: "newname"
        type: PATH
    }
    params {
        name: "flags"
        type: INT32
    }
}

syscall {
    name: "renameat"
    num: 264
    params {
        name: "olddfd"
        type: FD
    }
    params {
        name: "oldname"
        type: PATH
    }
    params {
        name: "newdfd"
        type: FD
    }
    params {
        name: "newname"
        type: PATH
    }
}

syscall {
    name: "rename"
    num: 82
    params {
        name: "oldname"
        type: PATH
    }
    params {
        name: "newname"
        type: PATH
    }
}

syscall {
    name: "chmod"
    num: 90
    params {
        name: "pathname"
        type: PATH
    }
    params {
        name: "mode"
        type: INT32
    }
}

syscall {
    name: "fchmod"
    num: 91
    params {
        name: "fd"
        type: FD
    }
    params {
        name: "mode"
        type: INT32
    }
}

syscall {
    name: "fchmodat"
    num: 268
    params {
        name: "dirfd"
        type: FD
    }
    params {
        name: "pathname"
        type: PATH
    }
    params {
        name: "mode"
        type: INT32
    }
    params {
        name: "flags"
        type: INT32
    }
}

syscall {
    name: "chown"
    num: 92
    params {
         name: "pathname"
         type: PATH
    }
    params {
        name: "owner" 
        type: INT32
    }
    params {
        name: "group"
        type: INT32
    }
}

syscall {
    name: "lchown"
    num: 94
    params {
         name: "pathname"
         type: PATH
    }
    params {
        name: "owner" 
        type: INT32
    }
    params {
        name: "group"
        type: INT32
    }
}

syscall {
    name: "fchown"
    num: 93
    params {
         name: "fd"
         type: FD
    }
    params {
        name: "owner" 
        type: INT32
    }
    params {
        name: "group"
        type: INT32
    }
}

syscall {
    name: "fchownat"
    num: 260
    params {
        name: "dirfd"
        type: FD
    }
    params {
        name: "pathname"
        type: PATH
    }
    params {
        name: "owner" 
        type: INT32
    }
    params {
        name: "group"
        type: INT32
    }
    params {
        name: "flags"
        type: INT32
    }
}


syscall {
    name: "utimensat"
    num: 280
    params {
        name: "dirfd"
        type: FD
    }
    params {
        name: "pathname"
        type: PATH
    }
    params {
        name: "times"
        type: IN_BUFFER
        const_len: 32
    }
    params {
        name: "flags"
        type: INT32
    }
}

syscall {
    name: "utimes"
    num: 235
    params {
        name: "filename"
        type: PATH
    }
    params {
        name: "times"
        type: IN_BUFFER
        const_len: 32
    }
}

syscall {
    name: "link"
    num: 86
    params {
        name: "oldname"
        type: PATH
    }
    params {
        name: "newname"
        type: PATH
    }
}

syscall {
    name: "socket"
    num: 41
    retval: FD
    params {
        name: "family"
        type: INT32
    }
    params {
        name: "type"
        type: INT32
    }
    params {
        name: "protocol"
        type: INT32
    }
}

syscall {
    name: "bind"
    num: 49
    params {
        name: "fd"
        type: FD
    }
    params {
        name: "umyaddr"
        type: IN_BUFFER
        len_param_name: "addrlen"
    }
    params {
        name: "addrlen"
        type: INT32
    }
}

syscall {
    name: "write"
    num: 1
    retval: INT32
    params {
        name: "fd"
        type: FD
    }
    params {
        name: "buf"
        type: IN_BUFFER
        len_param_name: "count"
    }
    params {
        name: "count"
        type: INT32
    }
}

syscall {
    name: "mount"
    num: 165
    params {
        name: "source"
        type: STRING
    }
    params {
        name: "target"
        type: STRING
    }
    params {
        name: "filesystemtype"
        type: STRING
    }
    params {
        name: "mountflags"
        type: INT32
    }
    params {
        name: "data"
        type: STRING
    }
}